export const BROWN_CONCENTRATIONS = [
  "Africana Studies",
  "American Studies",
  "Anthropology",
  "Applied Mathematics",
  "Applied Mathematics-Biology",
  "Applied Mathematics-Computer Science",
  "Applied Mathematics-Economics",
  "Archaeology and the Ancient World",
  "Architecture",
  "Astronomy",
  "Behavioral Decision Sciences",
  "Biochemistry and Molecular Biology",
  "Biology",
  "Biomedical Engineering",
  "Biophysics",
  "Business, Entrepreneurship and Organizations",
  "Chemical Physics",
  "Chemistry",
  "Classics",
  "Cognitive Neuroscience",
  "Cognitive Science",
  "Comparative Literature",
  "Computational Biology",
  "Computer Science",
  "Computer Science-Economics",
  "Computer Science-Mathematics",
  "Contemplative Studies",
  "Development Studies",
  "Early Modern World",
  "East Asian Studies",
  "Economics",
  "Education Studies",
  "Engineering",
  "Engineering and Physics",
  "English",
  "Environmental Studies",
  "Ethnic Studies",
  "French and Francophone Studies",
  "Gender and Sexuality Studies",
  "Geological Sciences",
  "Geological Sciences-Biology",
  "German Studies",
  "Hispanic Literatures and Cultures",
  "History",
  "History of Art and Architecture",
  "Independent Concentration",
  "International Relations",
  "Italian Studies",
  "Judaic Studies",
  "Latin American and Caribbean Studies",
  "Linguistics",
  "Literary Arts",
  "Mathematics",
  "Mathematics-Computer Science",
  "Mathematics-Economics",
  "Medieval Cultures",
  "Modern Culture and Media",
  "Music",
  "Neuroscience",
  "Philosophy",
  "Physics",
  "Physics and Philosophy",
  "Political Science",
  "Portuguese and Brazilian Studies",
  "Psychology",
  "Public Health",
  "Public Policy",
  "Religious Studies",
  "Science, Technology, and Society",
  "Slavic Studies",
  "Social Analysis and Research",
  "Sociology",
  "South Asian Studies",
  "Statistics",
  "Theatre Arts and Performance Studies",
  "Urban Studies",
  "Visual Art"
].sort() 